# Generated by Django 5.2.7 on 2025-10-28 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcgBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=64)),
                ('ts', models.DateTimeField(db_index=True)),
                ('fs_hz', models.PositiveIntegerField()),
                ('bpm', models.PositiveIntegerField()),
                ('n_samples', models.PositiveIntegerField()),
                ('ecg_blob', models.BinaryField()),
                ('compressed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['device_id', 'ts'], name='ingest_ecgb_device__0f9a4f_idx')],
            },
        ),
        migrations.CreateModel(
            name='InferenceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('score', models.FloatField()),
                ('latency_ms', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('buffer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inference', to='ingest.ecgbuffer')),
            ],
        ),
    ]
